export const cotizaciones = [
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-01",
    "fechaEntrega": "2024-09-02",
    "importe": 2000,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Juan Gonzalez",
    "calificacionTransportista": "4.5",
    "emailTransportista": "juangonzalez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-02",
    "fechaEntrega": "2024-09-03",
    "importe": 2200,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Ana Fernández",
    "calificacionTransportista": "4.2",
    "emailTransportista": "ana.fernandez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-03",
    "fechaEntrega": "2024-09-04",
    "importe": 2500,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Carlos López",
    "calificacionTransportista": "4.3",
    "emailTransportista": "carlos.lopez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-04",
    "fechaEntrega": "2024-09-05",
    "importe": 2700,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Laura Martínez",
    "calificacionTransportista": "4.1",
    "emailTransportista": "laura.martinez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-05",
    "fechaEntrega": "2024-09-06",
    "importe": 3000,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Miguel Torres",
    "calificacionTransportista": "4.0",
    "emailTransportista": "miguel.torres@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-06",
    "fechaEntrega": "2024-09-07",
    "importe": 3200,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Sofía García",
    "calificacionTransportista": "4.4",
    "emailTransportista": "sofia.garcia@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-07",
    "fechaEntrega": "2024-09-08",
    "importe": 3400,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Jorge Rodríguez",
    "calificacionTransportista": "4.3",
    "emailTransportista": "jorge.rodriguez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-08",
    "fechaEntrega": "2024-09-09",
    "importe": 3600,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Valeria Pérez",
    "calificacionTransportista": "4.6",
    "emailTransportista": "valeria.perez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-09",
    "fechaEntrega": "2024-09-10",
    "importe": 3800,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Fernando López",
    "calificacionTransportista": "4.5",
    "emailTransportista": "fernando.lopez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-10",
    "fechaEntrega": "2024-09-11",
    "importe": 4000,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "Tarjeta",
    "nroPago": "",
    "nombreTransportista": "Lucas García",
    "calificacionTransportista": "4.7",
    "emailTransportista": "gabriela.sanchez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-11",
    "fechaEntrega": "2024-09-12",
    "importe": 4200,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Ricardo Ramírez",
    "calificacionTransportista": "4.2",
    "emailTransportista": "ricardo.ramirez@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-12",
    "fechaEntrega": "2024-09-13",
    "importe": 4400,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Nicolás Morales",
    "calificacionTransportista": "4.1",
    "emailTransportista": "nicolas.morales@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-13",
    "fechaEntrega": "2024-09-14",
    "importe": 4600,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Daniela Vargas",
    "calificacionTransportista": "4.3",
    "emailTransportista": "daniela.vargas@gmail.com"
  },
  {
    "estado": "Pendiente",
    "fechaRetiro": "2024-09-14",
    "fechaEntrega": "2024-09-15",
    "importe": 4800,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Carlos Fernández",
    "calificacionTransportista": "4.4",
    "emailTransportista": "carlos.fernandez@gmail.com"
  },
  {
    "estado": "Confirmada",
    "fechaRetiro": "2024-09-15",
    "fechaEntrega": "2024-09-16",
    "importe": 5000,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "Contado contra entrega",
    "nroPago": "442313",
    "nombreTransportista": "Lucía Gómez",
    "calificacionTransportista": "4.5",
    "emailTransportista": "lucia.gomez@gmail.com"
  },
  {
    "estado": "Cancelada",
    "fechaRetiro": "2024-09-16",
    "fechaEntrega": "2024-09-17",
    "importe": 5200,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Andrés Silva",
    "calificacionTransportista": "4.6",
    "emailTransportista": "andres.silva@gmail.com"
  },
  {
    "estado": "Cancelada",
    "fechaRetiro": "2024-09-17",
    "fechaEntrega": "2024-09-18",
    "importe": 5400,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Patricia Mendoza",
    "calificacionTransportista": "4.2",
    "emailTransportista": "patricia.mendoza@gmail.com"
  },
  {
    "estado": "Cancelada",
    "fechaRetiro": "2024-09-18",
    "fechaEntrega": "2024-09-19",
    "importe": 5600,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Roberto García",
    "calificacionTransportista": "4.3",
    "emailTransportista": "roberto.garcia@gmail.com"
  },
  {
    "estado": "Cancelada",
    "fechaRetiro": "2024-09-19",
    "fechaEntrega": "2024-09-20",
    "importe": 5800,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Verónica Pérez",
    "calificacionTransportista": "4.4",
    "emailTransportista": "veronica.perez@gmail.com"
  },
  {
    "estado": "Cancelada",
    "fechaRetiro": "2024-09-20",
    "fechaEntrega": "2024-09-21",
    "importe": 6000,
    "formasPago": ["Tarjeta", "Contado al retirar", "Contado contra entrega"],
    "formaPagoSeleccionada": "",
    "nroPago": "",
    "nombreTransportista": "Javier Rodríguez",
    "calificacionTransportista": "4.5",
    "emailTransportista": "javier.rodriguez@gmail.com"
  }
];
